### PR TITLE
fix ollama streaming, to handle multiple objects

### PR DESCRIPTION
**Pull request by skadefro**

### CODE REVIEW

**Comment by zya** [comment]
@skadefro is this addressing the same thing as #3 ?

**Comment by ronneldavis** [comment]
@zya Yeah this seems to be addressing the same issue, I would recommend merging this though

**Comment by skadefro** [comment]
Oh, i had not seen there was already a PR fixing that. 
Feel free to close this PR then, if the other one already fixes it. ( but if you want to use this, i should remove a console.log i forgot to remove )

**Comment by zya** [comment]
Done in #3

**Pull request closed without merging**
